[package]
name = "laptop-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.161"
thiserror = "2.0.3"
log = "0.4.22"
env_logger = "0.11.5"
regex = "1.11.1"
plotters = "0.3.7"

[build-dependencies]
